name: Update Dependency Graph

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  dependency-graph:
    name: Update Dependency Graph

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Set up SBT launcher
        uses: sbt/setup-sbt@v1

      - name: SBT Dependency Submission
        uses: scalacenter/sbt-dependency-submission@v3
