name: Release
on:
  push:
    tags: [ "v*-RELEASE" ]

permissions:
  contents: write
  packages: write

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: sbt test

      - name: Create Release Package
        run: sbt universal:packageBin

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            target/universal/decorpyc-${{  github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            decorpyc-${{  github.ref_name }}.zip